//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarParts
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deliveries
    {
        public Deliveries()
        {
            this.Shipments = new HashSet<Shipments>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string TrackUrl { get; set; }
        public bool Deleted { get; set; }
        public Nullable<decimal> PriceForWeight { get; set; }
        public int InsurancePercentCost { get; set; }
    
        public virtual ICollection<Shipments> Shipments { get; set; }
    }
}
