//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarParts
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shipments
    {
        public Shipments()
        {
            this.ShipmentProducts = new HashSet<ShipmentProducts>();
        }
    
        public int Id { get; set; }
        public int CustomerId { get; set; }
        public Nullable<int> DeliveryId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> ReceiptDate { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public bool Insurance { get; set; }
        public Nullable<decimal> DeliveryCost { get; set; }
        public string ShippingNumber { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<decimal> Price { get; set; }
        public int CreatedBy { get; set; }
        public int ShipmentStatusId { get; set; }
        public bool Deleted { get; set; }
        public Nullable<decimal> Size { get; set; }
    
        public virtual Account Accounts { get; set; }
        public virtual ICollection<ShipmentProducts> ShipmentProducts { get; set; }
        public virtual Deliveries Deliveries { get; set; }
        public virtual ShipmentStatuses ShipmentStatuses { get; set; }
        public virtual Customers Customers { get; set; }
    }
}
